version: '3.1'
services:
  app:
    container_name: app-springboot-postgresql
    image: tenpo_api
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=gabi
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
